buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: npm install
  serveCommand: npx serve -p 8080
  previewReadyRegex: test-regex
serving:
  reverseProxyPrefix: https://stores.vegalocator.com/home
